import React from "react";
import RegisterPage from "./Register";

export const metadata = {
  title: "ลงทะเบียน",
  description: "Generated by create next app",
};

function Register() {
  return <RegisterPage />;
}

export default Register;
