import React from "react";
import List from "./List";


export const metadata = {
  title: "Users",
  description: "Generated by create next app",
};

function Users() {
  
  return (
    <>
      <List />
    </>
  );
}

export default Users;
