import React, { useEffect } from "react";
import HomePage from "./HomePage";


export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

interface Props {
  session?: { [key: string]: string | string[] | undefined };
}

async function Index() {
  return <HomePage />;
}

export default Index;
