import React from "react";
import HomePage from "./HomePage";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

function Index() {
  return <HomePage />;
}

export default Index;
