import React from "react";
import LoginPage from "./Login";

export const metadata = {
  title: "เข้าสู่ระบบ",
  description: "Generated by create next app",
};

interface IProps {
  searchParams?: { [key: string]: string | string[] | undefined };
}

const Login = ({ searchParams }: IProps) => {
  return <LoginPage props={searchParams} />;
};

export default Login;
