import EditUser from "./EditUser";

export const metadata = {
  title: "User",
  description: "Generated by create next app",
};

export default function User({ params }: { params: { id: number } }) {
  console.log(typeof params.id);

  const userId = params.id;

  return (
    <>
      <EditUser userId={params.id} />
    </>
  );
}
