import React, { useEffect } from "react";
import dynamic from "next/dynamic";

const Step = dynamic(() => import("../views/Steps/Step"), {
  ssr: false,
});

export const metadata = {
  title: "Step",
  description: "Generated by create next app",
};

async function Index() {
  return (
    <>
      <div className="container py-5">
        <h1 className="text-center">Step</h1>
      </div>
      <Step />
    </>
  );
}

export default Index;
